name: iOS App Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      test_suite:
        description: 'Test suite to run'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - smoke
          - regression

jobs:
  test:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Appium
      run: |
        npm install -g appium
        if appium driver list --installed | grep -q xcuitest; then
          appium driver update xcuitest
        else
          appium driver install xcuitest
        fi
        if appium driver list --installed | grep -q uiautomator2; then
          appium driver update uiautomator2
        else
          appium driver install uiautomator2
        fi
    
    - name: Start Appium Server
      run: appium &
      
    - name: Wait for Appium
      run: sleep 10
      
    - name: Run tests
      run: npm test 